# Generated by Django 5.1.15 on 2026-04-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Tự tạo từ tiêu đề, dùng làm URL bài viết', max_length=200, unique=True, verbose_name='URL slug')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('description', models.TextField(help_text='Hiển thị dưới tiêu đề ở danh sách bài viết', verbose_name='Mô tả SEO')),
                ('thumbnail', models.URLField(max_length=500, verbose_name='URL ảnh đại diện')),
                ('publish_day', models.CharField(default='01', help_text='Ví dụ: 22', max_length=10, verbose_name='Ngày')),
                ('publish_month', models.CharField(default='Jan', help_text='Ví dụ: May, Jun, Apr...', max_length=10, verbose_name='Tháng')),
                ('is_published', models.BooleanField(default=False, verbose_name='Đã xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('intro', models.TextField(help_text='Đoạn intro đầu bài viết (trong khung "Lời khuyên chuyên gia")', verbose_name='Lời giới thiệu')),
                ('service_desc', models.TextField(blank=True, help_text='Phần "Chi tiết dịch vụ tại LAPTOP PHÚ QUỐC"', verbose_name='Mô tả dịch vụ')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='blog.article')),
            ],
            options={
                'verbose_name': 'Lợi ích',
                'verbose_name_plural': 'Lợi ích khách hàng',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Ví dụ: "Kiểm tra và cắm lại cáp: 100.000đ - 200.000đ"', verbose_name='Nội dung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='blog.article')),
            ],
            options={
                'verbose_name': 'Mục báo giá',
                'verbose_name_plural': 'Báo giá tham khảo',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixes', to='blog.article')),
            ],
            options={
                'verbose_name': 'Giải pháp',
                'verbose_name_plural': 'Giải pháp xử lý',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='blog.article')),
            ],
            options={
                'verbose_name': 'Dấu hiệu',
                'verbose_name_plural': 'Dấu hiệu nhận biết',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='blog.article')),
            ],
            options={
                'verbose_name': 'Bước',
                'verbose_name_plural': 'Quy trình xử lý',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='Danh mục'),
        ),
    ]
