# Generated by Django 5.1.15 on 2026-04-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleStep',
        ),
    ]
