# Generated by Django 5.1.15 on 2026-04-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_articlestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='VD: Key 1, Key cá nhân...', max_length=100, verbose_name='Tên / Ghi chú')),
                ('api_key', models.CharField(max_length=200, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gemini API Key',
                'verbose_name_plural': 'Gemini API Keys',
                'ordering': ['label'],
            },
        ),
    ]
