# Generated by Django 5.1.15 on 2026-04-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=300, verbose_name='Tình trạng thiết bị')),
                ('predicted_issue', models.CharField(max_length=300, verbose_name='Dự đoán lỗi')),
                ('price_range', models.CharField(max_length=100, verbose_name='Chi phí dự kiến')),
                ('warranty', models.CharField(max_length=100, verbose_name='Thời hạn bảo hành')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Mục bảng giá',
                'verbose_name_plural': 'Bảng giá',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(verbose_name='Mô tả ngắn')),
                ('image', models.URLField(blank=True, max_length=500, verbose_name='URL hình ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='LAPTOP PHÚ QUỐC', max_length=200, verbose_name='Tên cửa hàng')),
                ('phone', models.CharField(default='0815 774 668', max_length=20, verbose_name='Số điện thoại')),
                ('zalo', models.CharField(default='0815 774 668', max_length=20, verbose_name='Zalo')),
                ('address', models.TextField(default='41C Lý Thường Kiệt, Dương Đông, Phú Quốc', verbose_name='Địa chỉ')),
                ('google_map_embed', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d125646.65348812896!2d103.86406068069593!3d10.224602600000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31a78b8eb1bb774f%3A0x46f1fc0b2b010ac9!2zTGFwdG9wIFBow7ogUXXhu5Fj!5e0!3m2!1svi!2s!4v1775486474591!5m2!1svi!2s', verbose_name='Google Maps embed URL')),
                ('morning_hours', models.CharField(default='8h - 12h', max_length=50, verbose_name='Giờ sáng')),
                ('afternoon_hours', models.CharField(default='14h - 19h', max_length=50, verbose_name='Giờ chiều')),
                ('working_days', models.CharField(default='Tất cả các ngày trong tuần', max_length=100, verbose_name='Ngày làm việc')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='URL Logo')),
                ('meta_title', models.CharField(blank=True, default='Laptop Phú Quốc - Sửa chữa laptop uy tín tại Phú Quốc', max_length=200, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, default='Dịch vụ sửa chữa laptop chuyên nghiệp tại Phú Quốc. Hơn 10 năm kinh nghiệm, linh kiện chính hãng, bảo hành dài hạn.', verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Cấu hình website',
                'verbose_name_plural': 'Cấu hình website',
            },
        ),
    ]
