# Generated by Django 5.1.15 on 2026-04-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, upload_to='config/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/', verbose_name='Hình ảnh'),
        ),
    ]
