# Generated by Django 5.1.15 on 2026-04-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ tên khách hàng')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('message', models.TextField(verbose_name='Nội dung cần hỗ trợ')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('processing', 'Đang xử lý'), ('done', 'Hoàn thành')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('admin_note', models.TextField(blank=True, help_text='Chỉ admin nhìn thấy, không hiển thị ra ngoài', verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
            ],
            options={
                'verbose_name': 'Yêu cầu tư vấn',
                'verbose_name_plural': 'Yêu cầu tư vấn',
                'ordering': ['-created_at'],
            },
        ),
    ]
